### ISSUE TITLE
Extension crashes when connecting to a remote workspace

### ISSUE THREAD

**Issue by bradzacher** [ast-grep/ast-grep-vscode#133]
I'm trying to use ast-grep when connecting to a remote dev server (managed via coder).
I have `ast-grep` installed both on my local (mac) machine and on the remote (linux) box and running `ast-grep lsp --help` on both shows the help output as expected.

However when I connect to the remote server the extension immediately crashes:

![image](https://github.com/ast-grep/ast-grep-vscode/assets/7462525/f435c985-62b4-4ca6-ace9-0f2d90d605d5)

<details>
<summary>ast-grep extension log</summary>

```
[Error - 10:42:15 AM] Client ast-grep language client: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 10:42:15 AM] Client ast-grep language client: connection to server is erroring.
write EPIPE
[Error - 10:42:15 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient2.shutdown (<vscode>/extensions/ast-grep.ast-grep-vscode-0.0.3/out/extension.js:15708:17)
	at LanguageClient2.stop (<vscode>/extensions/ast-grep.ast-grep-vscode-0.0.3/out/extension.js:15685:21)
	at LanguageClient2.stop (<vscode>/extensions/ast-grep.ast-grep-vscode-0.0.3/out/extension.js:18239:22)
	at LanguageClient2.handleConnectionError (<vscode>/extensions/ast-grep.ast-grep-vscode-0.0.3/out/extension.js:15928:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 10:42:15 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 10:42:15 AM] ast-grep language client client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 10:42:15 AM] Connection to server got closed. Server will restart.
true
sg: group 'lsp' does not exist
[Error - 10:42:15 AM] Server process exited with code 1.
[Error - 10:42:15 AM] Server process exited with code 1.
[Error - 10:42:15 AM] Client ast-grep language client: connection to server is erroring.
Cannot call write after a stream was destroyed
[Error - 10:42:15 AM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 10:42:15 AM] ast-grep language client client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 10:42:15 AM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 10:42:15 AM] Connection to server got closed. Server will restart.
true
sg: group 'lsp' does not exist
sg: group 'lsp' does not exist
[Error - 10:42:15 AM] Server process exited with code 1.
[Error - 10:42:15 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:42:15 AM] Connection to server got closed. Server will restart.
true
[Error - 10:42:15 AM] ast-grep language client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
sg: group 'lsp' does not exist
[Error - 10:42:15 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:42:15 AM] Connection to server got closed. Server will restart.
true
[Error - 10:42:15 AM] ast-grep language client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:42:15 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:42:15 AM] Server process exited with code 1.
sg: group 'lsp' does not exist
[Error - 10:42:15 AM] Server process exited with code 1.
[Error - 10:42:15 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:42:15 AM] The ast-grep language client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:42:15 AM] ast-grep language client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:42:15 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

</details>

What's the best way to help debug this further?

**Comment by HerringtonDarkholme** [comment]
Hi! Thanks for giving ast-grep vscode a try! 
I have no experience in remote server setup but I will give it a look later. 

Thanks for reporting.

**Comment by HerringtonDarkholme** [comment]
Oh! Would you like to change the configuration `astGrep.serverPath` to `ast-grep`? 

I have changed it https://github.com/ast-grep/ast-grep-vscode/commit/965741fbd6aa38137bcc1c7cbc64dcbeeb614131 but not managed to push it to release. 

From the crash log, I can see the error is `sg` group thing that may relate to linux shadow utils.

**Comment by bradzacher** [comment]
I changed it to `ast-grep` and it crashed in the same way.
Digging more it looks like this might be a misconfig on my end.
It looks like for some reason the server hasn't included the linux brew bin folder 🤔
I'll dig more - but this would probably be a good case to add an explicit error message for instead of just hard crashing.

**Comment by SoonIter** [comment]
@HerringtonDarkholme The user's environment is too complicated. We should consider integrating a cli binary package in ast-grep vscode extension to avoid similar situations which is the best solution in my opinion

In this way, we can get the following benefits.

1. make vscode extension work independently 
2. The version is always matched between `ast-grep` and `ast-grep-vscode`

More discussion about it and how to do it is needed

**Comment by bradzacher** [comment]
My problem was that brew had added its setup to `~/.bashrc` but not `~/.bash_profile`.
VSCode spawns the extension within a "non login" shell which means it loads `~/.bashrc` but not `~/.bash_profile`.

So that meant that by default the extension did not have brew in the path - and thus `sg`/`ast-grep` could not be found.
On linux there's also [an existing command called `sg`](https://man7.org/linux/man-pages/man1/sg.1.html) which further complicated the error messages!

The fix was to add the brew setup to `~/.bash_profile` so that it registered in both a login and a non-login shell.

---

But agree that either including the bin by default would be good to avoid setup issues.
But if you don't go that route - having some explicit checks for the configured binary would be good so the message can be like "the configured command didn't exist" instead of "CRASH AND BURN"

**Comment by HerringtonDarkholme** [comment]
Thank @bradzacher for all your kind suggestions! The new release 0.0.5 should solve most of them! 
The extension will have continuous improvements and I sincerely welcome new suggestions and feedbacks 😃
