### ISSUE TITLE
extension is unreadable on most dark themes

### ISSUE THREAD

**Issue by bradzacher** [ast-grep/ast-grep-vscode#134]
I'm using the "Dark+" colour theme and the search results renders poorly:

![image](https://github.com/ast-grep/ast-grep-vscode/assets/7462525/31594832-ff3e-41c1-8f57-b85ff358a920)

I tried a few different built-in dark themes and they all have the same problem of using black for the text: Abyss, "Dark (Visual Studio)", "Dark High Contrast", "Kimbie Dark", Monokai, "Monokai Dimmed", Red, "Solarized Dark", "Tomorrow Night Blue".

The only one that I could get to work was "Dark Modern" and OFC the light themes.

Particularly bad was the "Dark High Contrast" theme because it uses black as the background - so you have black text on a black background and the highlight is hidden:
![image](https://github.com/ast-grep/ast-grep-vscode/assets/7462525/0654c039-674e-462a-9614-e1365e565165)

**Comment by HerringtonDarkholme** [comment]
Thanks for the report!

**Comment by SoonIter** [comment]
related to #131, need more information about why different themes have different behaviors.
