### ISSUE TITLE
extension panel does not provide any feedback to let the user know it is searching

### ISSUE THREAD

**Issue by bradzacher** [ast-grep/ast-grep-vscode#135]
When you type in a search the extension does not show any feedback that it is working. This means it's really confusing - I'm not sure if the extension is processing or if I've typed the search wrong and hit zero results.
In comparison the built-in vscode search shows a little blue runner at the top of the panel to indicate that it's working.

It would be great if there was a "loading" indicator (ideally the same as the built-in search panel) to let the user know that things are happening.

**Comment by HerringtonDarkholme** [comment]
fixed by https://github.com/ast-grep/ast-grep-vscode/pull/141
