### ISSUE TITLE
allow limiting the search to specific sub-folders

### ISSUE THREAD

**Issue by bradzacher** [ast-grep/ast-grep-vscode#137]
At work we have a massive monorepo so most of the time when using the built-in search I've got it scoped to a sub folder using the "files to include" field in the UI. I often quick-scope the search using the "Find in Folder..." context action when you right-click on a folder in the explorer.

It would be great if the extension had similar functionality!

**Comment by HerringtonDarkholme** [comment]
Sure! It is on the roadmap. I will set up several milestones for the extension now so that multiple feature requests can have a rough timeline expectation :) 

This feature is useful but I may put it in later releases (after unreadable text fix and default linux command)
