### ISSUE TITLE
Support multi-line input in search and replace

### ISSUE THREAD

**Issue by SigureMo** [ast-grep/ast-grep-vscode#188]
Detecting multi-line patterns in languages with forced indentation (such as Python) is a bit tricky. Currently I can only search/rewrite by writing YAML rules, but it would be great if we could support multi-line input and multi-line replacement directly in the VS Code extension!

Currently built-in search and replace can insert line breaks via <kbd>Shift</kbd>+<kbd>Enter</kbd>. It looks like they are both implemented in textarea.

<img width="239" alt="image" src="https://github.com/ast-grep/ast-grep-vscode/assets/38436475/540eaf3a-1c16-4c1e-ba4d-ba349649a21b">

**Comment by HerringtonDarkholme** [comment]
Sure thing, contribution is welcome 🤗
