### ISSUE TITLE
Rewrite action adds garbled codes

### ISSUE THREAD

**Issue by SoonIter** [ast-grep/ast-grep-vscode#212]
<img width="427" alt="image" src="https://github.com/ast-grep/ast-grep-vscode/assets/79413249/c9a9c6e7-d762-4c9d-acc1-986f7b7696f1">

<img width="1449" alt="image" src="https://github.com/ast-grep/ast-grep-vscode/assets/79413249/870c82a5-ab55-4e45-8cdf-6462566587d1">

**Comment by HerringtonDarkholme** [comment]
thanks for the report!
