### ISSUE TITLE
Delay activation

### ISSUE THREAD

**Issue by hediet** [ast-grep/ast-grep-vscode#236]
I would guess that most users don't use this extension daily. However, it loads with VS Code every single time, so it often unnecessary slows down VS Code:

https://github.com/ast-grep/ast-grep-vscode/blob/631727f24520b0bce993dd7119cbbc1a181f992d/package.json#L35

I suggest to do the activation as late as possible (e.g. [onView](https://code.visualstudio.com/api/references/activation-events#onView)).

**Comment by HerringtonDarkholme** [comment]
thanks for the suggestion!
I have a question that the extension is also a linter that will be activated if the workspace has a project file, say sgconfig.yml, https://ast-grep.github.io/reference/sgconfig.html

And users can customize their project config name. Is there any way to activate the extension based on dynamic users' configuration?
