### ISSUE TITLE
[bug] outdated diff content when diff is changed

### ISSUE THREAD

**Issue by alexzhang1030** [ast-grep/ast-grep-vscode#282]
Outdated diff content when diff is changed, see ↓

https://github.com/ast-grep/ast-grep-vscode/assets/49969959/eacebad3-715b-4fbf-9e73-d0abdd71d75d

**Comment by HerringtonDarkholme** [comment]
this is weird, since `cleanupDocument` will be called when the diff view is closed.
and everything should be recomputed after reopening the diff

**Comment by HerringtonDarkholme** [comment]
And I cannot reproduce the issue locally. Can you provide the example repo? 

The onDidCloseTextDocument should have already done the cleaning up. 
https://github.com/ast-grep/ast-grep-vscode/blob/main/src/extension/preview.ts#L268-L273

**Comment by alexzhang1030** [comment]
Env:
- ast-grep `0.20.4`
- ast-grep `0.1.7`
- code `1.88.1 arm64`
- OS `macOS 14.2.1 (23C71)`

Reproduction step:
1. shell exec `pnpm create vite --name vite-project --template vue-ts`
2. cd `vite-project`
3. use ast-grep-vscode, search `createApp`, replace `createApp2`
4. click an item, check out the `diff` view
5. update replace text to `createApp3`
6. check out `diff` again, the `createApp2` still exists.

**Comment by alexzhang1030** [comment]
> And I cannot reproduce the issue locally. Can you provide the example repo?
> 
> The onDidCloseTextDocument should have already done the cleaning up. [`main`/src/extension/preview.ts#L268-L273](https://github.com/ast-grep/ast-grep-vscode/blob/main/src/extension/preview.ts?rgh-link-date=2024-04-19T19%3A02%3A23Z#L268-L273)

I guess this listener is not guaranteed triggered when a text document is closed. see the docs says:

![image](https://github.com/ast-grep/ast-grep-vscode/assets/49969959/cc5cad96-924a-4f45-a568-038cdd64a678)

This PR #281 makes sense; it avoids clearing the cache when the diff view is closed. This is beneficial in scenarios where the diff view is frequently reopened without any changes to the rewrite/search parameters.

**Comment by HerringtonDarkholme** [comment]
Maybe not. But I am not 100% sure. Pull request is welcome!
