### ISSUE TITLE
Extension causing hang on save with "Getting code actions from 'ast-grep VSCode:....."

### ISSUE THREAD

**Issue by evelant** [ast-grep/ast-grep-vscode#308]
Per the title, after installing the extension and setting up a config for my project saving files hangs on code actions. sg-grep works fine on the command line and the linting works fine in the editor. Only saving is the problem. There is no useful output in the output panel, only

```
[Info  - 1:33:30 PM] file opened!
Parsing doc.
Publishing init diagnostics.
```

**Comment by HerringtonDarkholme** [comment]
Would you mind having a reproduction repo so I can have a look? thanks!

**Comment by evelant** [comment]
I set `  "source.fixAll": "never` in `edit.codeActionsOnSave` in settings and that seems to have fixed it. I don't have a minimal reproduction at the moment.

**Comment by evelant** [comment]
Oops I guess I spoke too soon. That appeared to fix it but did not. It's still happening. I'll see if I can figure out a minimal reproduction.

**Comment by evelant** [comment]
🤦  and I had forgotten that I had a different setting for that in workspace config. With `"source.fixAll": "never"` the problem does not occur. It was happening with `"source.fixAll.eslint": "explicit",` so that's a clue.
