### ISSUE TITLE
Improve VSCode extension

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep-vscode#31]
# State of Art

* VsCode search
* https://codeque.co/get-started#vscode
* https://github.com/quasilyte/vscode-gogrep
* https://github.com/cshuaimin/ssr.nvim

# Feature List
* Single File Search 
* Project Files Search
* Replace preview 
* Replace All
* Include/Exclude files
* Toggle Context Line
* YAML mode
* Debug on Playground

**Comment by HerringtonDarkholme** [comment]
https://github.com/microsoft/vscode/issues/98098

**Comment by pd4d10** [comment]
VSCode seems only support [JSON schema validation](https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings).

For YAML, we probably need third-party extensions, such as https://github.com/redhat-developer/vscode-yaml

**Comment by pd4d10** [comment]
Figured out a way to get YAML intelliSense:

1. Install [VSCode YAML](https://github.com/redhat-developer/vscode-yaml) extension
2. Add config below to `.vscode/settings.json`
    ```jsonc
    {
      // ...
      "yaml.schemas": {
        "https://raw.githubusercontent.com/ast-grep/ast-grep/main/schema/project.json": "sgconfig.yml"
      }
    }
    ```

The schema needs to be accessible via URL, another PR here: https://github.com/ast-grep/ast-grep/pull/543

It's a little verbose, but would work.

**Comment by HerringtonDarkholme** [comment]
@pd4d10  looks like yaml language server is a better choice. https://github.com/redhat-developer/yaml-language-server

**Comment by HerringtonDarkholme** [comment]
Hi @pd4d10, I also added rule schema in https://github.com/ast-grep/ast-grep/blob/main/schemas/rule.json

**Comment by HerringtonDarkholme** [comment]
tree view source code
https://github.com/microsoft/vscode/blob/983a3bc0aecfc0772dd7b37919d7da36c89a6f2d/src/vs/workbench/browser/parts/views/treeView.ts

**Comment by HerringtonDarkholme** [comment]
tree view css
https://github.com/microsoft/vscode/blob/983a3bc0aecfc0772dd7b37919d7da36c89a6f2d/src/vs/workbench/browser/parts/views/media/views.css#L4

**Comment by HerringtonDarkholme** [comment]
![image](https://github.com/ast-grep/ast-grep-vscode/assets/2883231/f2873694-3b5c-4199-8e6e-e01bdf199730)
<img width="1335" alt="image" src="https://github.com/ast-grep/ast-grep-vscode/assets/2883231/9bc95eab-17ff-495f-ad02-644ce20a887a">

<img width="521" alt="image" src="https://github.com/ast-grep/ast-grep-vscode/assets/2883231/2d6640b7-4a09-4036-b4a1-7cea866ab434">
<img width="627" alt="image" src="https://github.com/ast-grep/ast-grep-vscode/assets/2883231/39b56e35-4dc8-4920-ae66-ef8ae7ad229d">
