### ISSUE TITLE
Open VSX Registry

### ISSUE THREAD

**Issue by jshwlkr** [ast-grep/ast-grep-vscode#372]
I can't seem to find ast-grep on the Open VSX registry (https://open-vsx.org/). It is likely we could see it there eventually or not?

**Comment by HerringtonDarkholme** [comment]
Contribution welcome to add a new github action for vsx!
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#github-action

**Comment by HerringtonDarkholme** [comment]
Added by @herrwusel Thanks!
