### ISSUE TITLE
Is there a trick to matching to `()` call?

### ISSUE THREAD

**Issue by JasonKleban** [ast-grep/ast-grep-vscode#401]
SG AST-GREP vscode is working for me in some cases (so it's wired up), but parentheses for a function call are not working.  So pattern `format` works, but pattern `format($A)` does not find `format(data)` for example.  I'm on Windows, btw.  I'm surprised I can't find any mention of this.

**Comment by HerringtonDarkholme** [comment]
What language are you using? It's probably already mentioned in the doc

https://ast-grep.github.io/catalog/c/#match-function-call-in-c

**Comment by JasonKleban** [comment]
Thanks!  I'm using typescript (.ts files, not .tsx _yet_) and the commandline `sg --pattern 'format($A)' --lang ts` is working for me.  Just not the VSCode extension when `(` `)` are involved.

**Comment by HerringtonDarkholme** [comment]
Please provide a minimal reproduction and also check your setting

<img width="400" alt="image" src="https://github.com/user-attachments/assets/e149007d-628b-4cc1-8d0c-fd48cdfcdc01">

**Comment by JasonKleban** [comment]
OK, I found my way to this extension through a back alleyway and so I didn't know to fully set up the environment.

I guess perhaps a simple term doesn't require a working LSP but the parentheses do.  Without the sgconfig.yml, the search for `format` finds matches.  Checking the ~hidden Output Log of "ast-grep" gave me the full diagnosis.

![image](https://github.com/user-attachments/assets/fa041dc9-8aa9-4a2d-9966-b6d578ce5f77)

(Could this empty sgconfig.yml just be assumed?  Even with no ruleDirs set, it seems to work.)

**Comment by JasonKleban** [comment]
> ~~Even with no ruleDirs set, it seems to work.~~

No, it doesn't work well with the empty file.  And neither does `sg` (silently finds no matches) but if I get rid of the sgconfig.yml `sg` works again.

**Comment by HerringtonDarkholme** [comment]
You have to have a valid configuration file or have no configuration at all

**Comment by HerringtonDarkholme** [comment]
I believe it's your problem. If you can help providing a minimal reproduction we can help you.
